pushFilePrefix("rules/")
mark = ruleGML("markForConversion.gml")
removeSingleR = ruleGML("removeSingleR.gml")
reattachExternal = ruleGML("reattachExternalEdge.gml")
removeAttached = ruleGML("removeAlreadyAttached.gml")
removeInterR = ruleGML("removeInterREdge.gml")
unmark = ruleGML("unmarkCollapsedNode.gml")
popFilePrefix()
